mesh_files:
  base:
    visual:
      mesh: "package://ur3/meshes/ur3/visual/base.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur3/meshes/ur3/collision/base.stl"

  shoulder:
    visual:
      mesh: "package://ur3/meshes/ur3/visual/shoulder.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur3/meshes/ur3/collision/shoulder.stl"

  upper_arm:
    visual:
      mesh: "package://ur3/meshes/ur3/visual/upperarm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur3/meshes/ur3/collision/upperarm.stl"
      mesh_files:

  forearm:
    visual:
      mesh: "package://ur3/meshes/ur3/visual/forearm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur3/meshes/ur3/collision/forearm.stl"

  wrist_1:
    visual:
      mesh: "package://ur3/meshes/ur3/visual/wrist1.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur3/meshes/ur3/collision/wrist1.stl"
    visual_offset: -0.085

  wrist_2:
    visual:
      mesh: "package://ur3/meshes/ur3/visual/wrist2.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur3/meshes/ur3/collision/wrist2.stl"
    visual_offset: -0.083

  wrist_3:
    visual:
      mesh: "package://ur3/meshes/ur3/visual/wrist3.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur3/meshes/ur3/collision/wrist3.stl"
    visual_offset: -0.082
    visual_offset_xyz: "0 -0.00255 -0.082"
  probe:
    visual:
      mesh: "package://ur3/meshes/ur3/visual/linescan.dae"  # 替换为你的探针STL路径
      material:
        name: "ProbeColor"
        color: "0.8 0.2 0.2 1.0"  # 自定义颜色 (RGBA)
    collision:
      mesh: "package://ur3/meshes/ur3/collision/linescan.stl"  # 碰撞模型路径（可与视觉相同）
    # 探针相对于 wrist_3_link 的安装偏移（根据实际设计调整）
    visual_offset_xyz: "0 0.175 -0.017" 
